apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemeral-volume-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemeral-demo
  template:
    metadata:
      labels:
        app: ephemeral-demo
    spec:
      containers:
        - name: writer
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - >
              while true; do
                echo "Hello from writer at $(date)" >> /shared/message.log;
                sleep 5;
              done
          volumeMounts:
            - name: shared-data
              mountPath: /shared

        - name: reader
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo "Starting reader..."; 
              tail -f /shared/message.log;
          volumeMounts:
            - name: shared-data
              mountPath: /shared

      volumes:
        - name: shared-data
          emptyDir: {}
