version: '1.0'

services:
  db:
    image: postgres
    container_name: postgresTest_1   
    restart: always
    environment:                 
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
