apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-demo-pvc
spec:
  storageClassName: manual      # must match PV's storageClassName
  accessModes:
    - ReadWriteMany             # must match PV's accessModes
  resources:
    requests:
      storage: 1Gi              # must be ≤ PV's capacity
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-demo-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sleep", "3600"]   # keep the pod running
      volumeMounts:
        - mountPath: /mnt/nfs
          name: nfs-storage
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-demo-pvc
