apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-demo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /nfsshare   #your specified path  you want
    server: 172.17.0.1   # your host machine IP
