apiVersion: apps/v1  #deployment was later realse in apps/v1 api only 
kind: Deployment
metadata:
  name: nginx-deployment 
  namespace: backend  
spec:
  replicas: 3
  selector:
    matchLabels:           
      app: nginx
  template:                
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
